const NOTIFICATION_EVENTS = {
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_UPDATED: 'TASK_UPDATED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  ITERATION_ADDED: 'ITERATION_ADDED',
  TASK_OVERDUE: 'TASK_OVERDUE',
};

module.exports = { NOTIFICATION_EVENTS };
